텐서플로우 행렬의 표현

In [37]:
import tensorflow as tf

In [38]:
input_data = [
    [1,1,1],[2,2,2]
]

In [44]:
x = tf.placeholder(dtype=tf.float32, shape=[2,3])
w = tf.Variable([[2],[2],[2]], dtype=tf.float32)
b = tf.Variable([4], dtype=tf.float32)

In [48]:
y = tf.matmul(x, w) + b

### 텐서플로우에서 행렬의 곱은 일반 * 을 사용하지 않고, 텐서플로우 함수 tf.matmul을 사용한다.

In [46]:
x.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [50]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y, feed_dict={x:input_data})

#텐서플로우에서 행렬 차원용어
# 행렬이 아닌 숫자나 상수 0 차원 : 스칼라
# 1차원행렬 : 벡터
# 2차원행렬 : 매트릭스
# 3차원행렬 : 3-Tensor 또는 큐브
# 그 이상의 다차원행렬 : n-tensor
# reduce_sum

In [51]:
x = [
    [1,1,1], [1,1,1]
]

In [52]:
tf.rank(x).eval(session = sess) # 자연수 2

2

In [53]:
tf.reduce_sum(x, axis=0).eval(session=sess) 
#axis 파라미터는 제거할 축
# reduce all dim 전체합을 구하라 ( 1 + 1 + 1 + 1 + 1 + 1  = 6)
# 그결과 모든 차원이 제거되고 단 하나의 스칼라 값이 출력됨

array([2, 2, 2])

In [54]:
tf.reduce_sum(x, axis=1).eval(session=sess)
# 1 인덱스 차원을 제거하고 0 인덱스 차원에 합해라
#[1+1+1=3, 1+1+1=3] #array([3,3])

array([3, 3])

In [55]:
tf.reduce_sum(x, axis=1, keepdims = True ).eval(session=sess)
# 1 인덱스 차원제거를 위해 0 인덱스 차원에 합한다 [1+1+1=3,1+1+1=3]
#keepdims은 결과를 얻고 최초차원을 유지해라
# array[[3],[3]]


array([[3],
       [3]])

reduce_mean 함수

In [56]:
x=[
    [2,2],[3,3]
]
tf.reduce_mean(x).eval(session=sess)
#reduce all dim 전체 평균을 구한다 (2+2+3+3)/4 = 2.5
# 모든 차원이 제거되고 단하나의 스칼라값이 출력된다

2